// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqtan3AGNmDx0Gi5qAYlGTI7VzxJHQ1JY',
    appId: '1:901197727801:web:5ee94f86fef29ea66365e8',
    messagingSenderId: '901197727801',
    projectId: 'esign-26b5b',
    authDomain: 'esign-26b5b.firebaseapp.com',
    storageBucket: 'esign-26b5b.firebasestorage.app',
    measurementId: 'G-YGRRJLC680',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCou6LPeK53xU2iagfF_TZ30wqjnBTrqIg',
    appId: '1:901197727801:android:a2b4bab6e76b6c1e6365e8',
    messagingSenderId: '901197727801',
    projectId: 'esign-26b5b',
    storageBucket: 'esign-26b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ys2HnjdJIYDB1MQ_gUOAE1I0299PS6c',
    appId: '1:901197727801:ios:a183b3aa1be163246365e8',
    messagingSenderId: '901197727801',
    projectId: 'esign-26b5b',
    storageBucket: 'esign-26b5b.firebasestorage.app',
    iosBundleId: 'com.example.eSign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ys2HnjdJIYDB1MQ_gUOAE1I0299PS6c',
    appId: '1:901197727801:ios:a183b3aa1be163246365e8',
    messagingSenderId: '901197727801',
    projectId: 'esign-26b5b',
    storageBucket: 'esign-26b5b.firebasestorage.app',
    iosBundleId: 'com.example.eSign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqtan3AGNmDx0Gi5qAYlGTI7VzxJHQ1JY',
    appId: '1:901197727801:web:9a160029eb7e93206365e8',
    messagingSenderId: '901197727801',
    projectId: 'esign-26b5b',
    authDomain: 'esign-26b5b.firebaseapp.com',
    storageBucket: 'esign-26b5b.firebasestorage.app',
    measurementId: 'G-SMDPR3BTYV',
  );
}
